### ISSUE TITLE
(bug): Unhandled promise rejection TypeError: null is not a function in iOS

### ISSUE THREAD

**Issue by ericbrumfield** [EinfachHans/cordova-plugin-advanced-imagepicker#30]
# Bug Report
I've been successfully using this plugin, which has been great in version 1.2.0.  Recently I have been updating our Ionic 4 project packages and updated this plugin from 1.2.0 to 1.5.4.  Now when either importing the typescript definition or using window.AdvancedImagePicker I get the error 'Unhandled promise rejection TypeError: null is not a function' in iOS.  This plugin is working for our older app that is using cordova-ios 5.1.1.  I can't seem to get it to work now after updating it to 1.5.4 using cordova-ios 6.1.0 or with latest cordova-ios 6.2.0.

**Current Behavior:**

When navigating to our app screens that import or use this plugin via window.AdvancedImagePicker the plugin no longer works, the ionic screen glitches regarding top and bottom panels in the UI and the simulator spams the message 'Unhandled promise rejection TypeError: null is not a function' to infinity.  This will happen for me now if using only the typescript definition import, the button that opens the picker does not have to be invoked, only the presence of the import statement will do it.

**Expected Behavior:**

I'd expect the image picker window/modal to open and display, but it doesn't open.

**Steps to reproduce:**

**Screenshots:**

**Environment information:**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- ios 6.1.0
- Plugins & versions installed in project (including this plugin)
    - branch-cordova-sdk 4.2.4 "branch-cordova-sdk"
    - com-badrit-base64 0.2.0 "Base64"
    - com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
    - cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
    - cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
    - cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
    - cordova-plugin-advanced-imagepicker 1.4.0 "AdvancedImagePicker"
    - cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
    - cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
    - cordova-plugin-app-version 0.1.12 "AppVersion"
    - cordova-plugin-background-geolocation 1.0.6 "CDVBackgroundGeoLocation"
    - cordova-plugin-camera 6.0.0 "Camera"
    - cordova-plugin-device 2.0.3 "Device"
    - cordova-plugin-dialogs 2.0.2 "Notification"
    - cordova-plugin-file 6.0.2 "File"
    - cordova-plugin-file-transfer 1.7.1 "File Transfer"
    - cordova-plugin-filechooser 1.2.0 "File Chooser"
    - cordova-plugin-filepath 1.6.0 "cordova-plugin-filepath"
    - cordova-plugin-filepicker 1.1.6 "File Picker"
    - cordova-plugin-geolocation 4.1.0 "Geolocation"
    - cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
    - cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
    - cordova-plugin-purchases 0.3.2 "Purchases"
    - cordova-plugin-statusbar 2.4.3 "StatusBar"
    - cordova-plugin-telerik-imagepicker 2.3.5 "ImagePicker"
    - cordova-plugin-whitelist 1.3.5 "Whitelist"
    - cordova-plugin-x-socialsharing 6.0.3 "SocialSharing"
    - cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
    - cordova-sqlite-storage 6.0.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
    - es6-promise-plugin 4.2.2 "Promise"
- Dev machine OS and version, e.g.
    - OSX
        - macOS 11.6.1 build 20G224

**Additional information**

This project the plugin is being used in is on Ionic 4 and is on Angular 7.  Xcode version is 13.1.  Cocoapod version 1.11.2.  ionic cli 5.4.16.  Would appreciate any ideas to try to remedy on my end or ways to isolate bug further.
